# Generated by Django 5.1.7 on 2025-06-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0002_remove_customuser_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
