# Generated by Django 5.1.7 on 2025-06-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0005_customuser_bookmark_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name_bookmark', models.CharField(blank=True, max_length=50, null=True)),
                ('bookmark_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bookmark_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='course_name_bookmark',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userRegister.bookmark'),
        ),
    ]
