# Generated by Django 5.1.7 on 2025-06-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0006_bookmark_remove_customuser_bookmark_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmark', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
