# Generated by Django 5.1.7 on 2025-06-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0008_alter_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmark_url',
        ),
    ]
