# Generated by Django 5.1.7 on 2025-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0009_remove_bookmark_bookmark_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
