# Generated by Django 5.1.7 on 2025-06-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0010_bookmark_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
