# Generated by Django 5.1.7 on 2025-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0011_alter_bookmark_bookmark_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='instructor_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='instructor_qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
