# Generated by Django 5.2.4 on 2025-09-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegister', '0012_bookmark_course_name_bookmark_instructor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
