# Generated by Django 5.1.7 on 2025-06-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0003_course_no_of_modules_module_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
