# Generated by Django 5.1.7 on 2025-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0004_remove_module_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='videos',
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.CharField(default='ff', max_length=1000),
            preserve_default=False,
        ),
    ]
