# Generated by Django 5.1.7 on 2025-06-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0005_remove_module_videos_module_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_enroled',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
