# Generated by Django 5.1.7 on 2025-06-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0006_course_total_enroled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='total_enroled',
            new_name='total_enrolled',
        ),
    ]
