# Generated by Django 5.1.7 on 2025-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0007_rename_total_enroled_course_total_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_enrolled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
