# Generated by Django 5.1.7 on 2025-06-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0008_alter_course_total_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_enrolled',
        ),
    ]
