# Generated by Django 5.2.4 on 2025-09-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avgRating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
