# Generated by Django 5.2.4 on 2025-09-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0011_course_avgrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
