# Generated by Django 5.2.4 on 2025-09-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0012_review_createdat_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avgRating',
            field=models.IntegerField(default=0),
        ),
    ]
