# Generated by Django 5.2.4 on 2025-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCourses', '0013_alter_course_avgrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
    ]
